#!/bin/sh
scrot --silent /tmp/scrt.png
ffmpeg -loglevel quiet -y -i /tmp/scrt.png -vf "gblur=sigma=15" /tmp/blur.png

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#494345'
TEXT='#dad7d9'
WRONG='#880000bb'
VERIFYING='#70a1d0'
i3lock \
	--insidever-color=$CLEAR     \
	--ringver-color=$VERIFYING   \
	\
	--insidewrong-color=$CLEAR   \
	--ringwrong-color=$WRONG     \
	\
	--inside-color=$BLANK        \
	--ring-color=$DEFAULT        \
	--line-color=$BLANK          \
	--separator-color=$DEFAULT   \
	\
	--verif-color=$TEXT          \
	--wrong-color=$TEXT          \
	--time-color=$TEXT           \
	--date-color=$TEXT           \
	--layout-color=$TEXT         \
	--bshl-color=$WRONG          \
	\
	--screen 1                   \
	--blur 5                     \
	--clock                      \
	--indicator                  \
	--time-str="%H:%M:%S"        \
	--date-str="%A, %Y-%m-%d"       \
	-i /tmp/blur.png

rm /tmp/scrt.png /tmp/blur.png
