#!/bin/sh
#
#
#STARTUP SCRIPT M8

#Flip monitors and set gamer refresh rate
xrandr --output DP-3 --right-of HDMI-1 --mode 1920x1080 --rate 144
#Set weeb wallpaper
feh --bg-fill ~/Pictures/walls/balcony.png --bg-fill ~/Pictures/walls/roof.jpg


