#!/bin/sh
#
#
#STARTUP SCRIPT M8

#Flip monitors and set gamer refresh rate
xrandr --output DisplayPort-2 --right-of HDMI-A-0 --mode 1920x1080 --rate 144
#feh --bg-fill ~/Pictures/walls/red.png 
#--bg-fill ~/Pictures/walls/roof.jpg


#feh --bg-fill ~/Pictures/walls/usareimu.jpg 
feh --bg-fill ~/Pictures/walls/rock.jpg 
#feh --bg-fill ~/Pictures/walls/ass.jpg 
#feh --bg-fill ~/Pictures/walls/balcony.png 

