#!/bin/sh
#
#
#STARTUP SCRIPT M8

#Flip monitors and set gamer refresh rate
xrandr --output DisplayPort-2 --right-of HDMI-0 --mode 1920x1080 --rate 144
#Set weeb wallpaper
feh --bg-fill ~/Pictures/walls/orange.jpg --bg-fill ~/Pictures/walls/ledge.png



clear
